name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: true
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Add conda to system path
      run: |
        echo $CONDA
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo $GITHUB_PATH
    - name: Install conda dependencies
      run: |
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda
        conda update conda-build
        conda install "viennarna>=2.5.1"
    - name: Install package 
      run: |
        conda install flit
        python -m pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
